spring.application.name=JBDL11_Redis
#spring.data.redis.host=redis-17216.crce179.ap-south-1-1.ec2.cloud.redislabs.com
#spring.data.redis.port=17216
#spring.data.redis.password=f4oVgHfRWUX9wEJoxIL94QFNLSY7nYX2
#spring.data.redis.username=default